server:
  port: 8082
spring:
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/mycinema
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: microservice-consumer-movie-ribbon-properties-cutomizing
mybatis:
  mapper-locations:
  - classpath*:mapper/*.xml
  type-aliases-package: com.itmuch.cloud.entity    
logging:
  level:
    root: info
    com.itmuch: debug
eureka: 
  client:
#作用：Eureka’s Health Checks
    healthcheck: 
      enabled: true
    service-url:
      #user登录eureka服务器需要用户名和密码：把http://localhost:8761/eureka/ 改成http://user:password123@localhost:8761/eureka
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    #设置为true，可以使用ip访问
    prefer-ip-address: true
    #自定义eureka的instanceID：例子——microservice-provider-user:8080(默认主机名:应用名称:应用端口)
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#作用：用于配置文件配置Ribbon      
microservice-provider-user: 
  ribbon: 
    #作用：配置负载均衡的规则，负载均衡的规则有很多Random规则，加权优先级规则（com.netflix.loadbalancer.WeightedResponseTimeRule）等等
    #此规则只适用于VIP为microservice-provider-user的RibbonClient，其他RibbonClient无效
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule