#设置认证eruka服务器的密码
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8761
#register-with-eureka: false和fetch-registry: false表示只把这个eruka当做server，不把它当做client
#defaultZone: http://localhost:9761/eureka：你想把eruka注册到哪个url
eureka:
  client: 
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #认证Eureka服务器：把http://localhost:8761/eureka改成http://user:password@localhost:8761/eureka
      defaultZone: http://user:password123@localhost:8761/eureka